name: rest_dart
version: 0.1.0
author: Matthew Barbour
description: A library for automating much of the minutia of creating a rest interface
homepage: https://github.com/sanmadjack/rest_dart
environment:
  sdk: 1.3.6
dependencies:
  logging: any
