name: rest_server
version: 0.1.2
author: Matthew Barbour <sanmadjack@gmail.com>
description: A dart library for automating much of the minutia of creating a rest server
homepage: https://github.com/sanmadjack/rest_server
environment:
  sdk: 1.5.8
dependencies:
  logging: any
  mime: any
  path: any
