name: rest_dart
version: 0.1.2
author: Matthew Barbour <sanmadjack@gmail.com>
description: A library for automating much of the minutia of creating a rest interface
homepage: https://github.com/sanmadjack/rest_dart
environment:
  sdk: 1.5.2
dependencies:
  logging: any
  mime: any
  path: any
